language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  # white list:
    # www.techug.com
    # www.awesomes.cn
- awesome_bot README.md --allow-redirect -w www.techug.com,www.awesomes.cn