language: ruby
rvm:
  - 2.4.1
branches:
  only:
  - danger
  except:
  - master
before_script:
  - gem install awesome_bot
  - gem install bundle
script:
  # white list:
    # www.techug.com
    # www.awesomes.cn
    # regexr.com
    # html5test.com
    # codepen.io
    # www.zhihu.com
- awesome_bot README.md --allow-redirect --allow-dupe --allow-ssl --allow 403 -w www.techug.com,www.awesomes.cn,regexr.com,html5test.com,codepen.io,www.zhihu.com
- bundle exec danger