name: check_url_by_awesome_bot

on:
  push:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Checks
      run: |
        gem install awesome_bot
        awesome_bot README.md --allow-redirect --allow-dupe --allow-ssl --allow 403 -w www.techug.com,www.awesomes.cn,regexr.com,html5test.com,codepen.io,www.zhihu.com